on:
  push:
    branches: [main]
    paths:
      - 'packages/ponder/**'
      - '.github/workflows/workstation-development.yml'

jobs:
  deploy:
    runs-on: [self-hosted, raihanard]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate .env file from selected system env
        working-directory: ./packages/ponder
        run: |
          env | grep -v '^_' | grep -v '^PWD=' | grep -v '^HOME=' | grep -v '^GITHUB' > .env

      - name: Print .env contents (debug)
        working-directory: ./packages/ponder
        run: cp ../../../../../.env .env

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies (monorepo)
        run: bun install

      - name: Change directory to packages/ponder
        working-directory: ./packages/ponder
        run: echo "Changed to Ponder"

      - name: Start or Reload Ponder via PM2
        working-directory: ./packages/ponder
        run: pm2 restart ponder
